---
name: Test Linux Python 3.8

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/ansible_toolbox/**'
      - 'tests/**'

permissions:
  contents: read
  pull-requests: read

jobs:
  execute-tests:
    uses: ./.github/workflows/test-suite-template.yml
    with:
      os-flavors: '["ubuntu-latest"]' 
      python-versions: '["3.8"]'
      